spring.application.name=PVH_GROUP_02_SPRING_MINI_PROJECT
server.port=9090
spring.datasource.url=jdbc:postgresql://localhost:5432/mini_spring_boot
spring.datasource.username=postgres
spring.datasource.password=endy123$$&&
mybatis.configuration.map-underscore-to-camel-case=true