spring.application.name=PVH_GROUP_02_SPRING_MINI_PROJECT
spring.datasource.url=jdbc:postgresql://localhost:5432/mini_spring_boot
server.port=8080
spring.datasource.username=postgres
spring.datasource.password=123

spring.servlet.multipart.enabled=true
spring.servlet.multipart.file-size-threshold=2KB
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=30MB

spring.file-upload-path=src/main/resources/files
mybatis.configuration.map-underscore-to-camel-case=true

rustfs.url=http://localhost:9000
rustfs.access.name=rustfsadmin
rustfs.access.secret=rustfsadmin
rustfs.bucket.name=demo-file-upload

logging.level.org.springframework.security=ERROR